### ISSUE TITLE
SSL for osci.io

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-infrastructure#15]
We are close to migrating everything from one host to another, so we started to use `.osci.io` so we can see results directly on the new machine. However, we having problems with HTTPS now.

@duck-rh is it possible to create certs for ssl? let's encrypt for example?
Ping me if you have any questions.

**Comment by duck-rh** [comment]
As the DNS does not point to the new host we cannot use the usual webroot Let's Encrypt method. I then used the DNS challenge manually to get the certificate. A patch to the role follows.

Please note that:
* since ns3.redhat.com is causing problems (again) I had to disable it in the zone to make the challenge work
* when switching to migration we would need to revoke the certificate and let the httpd role recreate it with the usual method or the renewal will not work
