### ISSUE TITLE
Store Ansible Vault key to GH secrets

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-infrastructure#34]
Hi @duck-rh,

Can you please store Ansible Vault key to GH repo secrets[0]?
This will help us to automate the sync of this repo (merged changes) and upstream server.

[0] https://github.com/beaker-project/beaker-infrastructure/settings/secrets/actions

**Comment by duck-rh** [comment]
I have created a `Ansible` environment with the `ANSIBLE_VAULT_PASSWORD` variable. Since Ansible does not allow passwords directly I would suggest that the CI creates a file with the content of this variable and reference the path in `ANSIBLE_VAULT_PASSWORD_FILE` (so that we do not have to specify it for each and every command).

The environment requires reviewers: currently it's us two but I would suggest we create an infra team with a list of trusted people to simplify the ACL.

The environment is currently only allowed on master since I believe we do not want anything unmerged to be run, but that can be changed is needed.

**Comment by StykMartin** [comment]
Great. Thank you @duck-rh. I will try to create a proper workflow w/ this.
